### ISSUE TITLE
XCode10 CI tests are failing 

### ISSUE THREAD

**Issue by greglandrum** [rdkit/neo4j-rdkit#3]
I'm not enough of a Java wizard to figure out what's going on here and don't have an XCode10 machine available to try on my own, but the Travis-CI builds for XCode10 are regularly failing. Here's an example from the `dev` branch:
https://travis-ci.com/rdkit/neo4j-rdkit/jobs/232173334

@evgerher @sarmbruster : any thoughts on how we can deal with this? Given that the other CI builds are passing, I'm happy to either ignore it or disable the XCode10 builds, but that's not a great long-term solution. Something seems to have changed that is interfering with Evgeniy's code that extracts native libraries from the jar file and saves a temp copy.

**Comment by sarmbruster** [comment]
@evgerher  I think the relevant stacktrace ist this one
```Caused by: java.lang.NoSuchFieldException: usr_paths

	at java.base/java.lang.Class.getDeclaredField(Class.java:2412)

	at org.rdkit.neo4j.bin.LibraryMover.addLibraryPath(LibraryMover.java:244)

	at org.rdkit.neo4j.bin.LibraryMover.createTempLibraryPath(LibraryMover.java:231)

	at org.rdkit.neo4j.bin.LibraryMover.resolveMissingLibraries(LibraryMover.java:61)

	... 48 more```
